export interface WorkerEnv {
	DB: D1Database;
	WHATSAPP_API_VERSION: string;
	WHATSAPP_WEBHOOK_VERIFY_TOKEN: string;
	WHATSAPP_ACCESS_TOKEN: string;
	WHATSAPP_PHONE_NUMBER_ID: string;
	WHATSAPP_TEMPLATE_LANGUAGE: string;
	WHATSAPP_INITIAL_TEMPLATE_NAME: string;
	WHATSAPP_REMINDER_TEMPLATE_NAME: string;
	WHATSAPP_AVAILABILITY_TEMPLATE_NAME: string;
	AUTOMATION_ENABLED: string;
    DASHBOARD_USERNAME: string;
    DASHBOARD_PASSWORD: string;
    WHATSAPP_APP_SECRET: string;
}
