import { managementPrincipalFromRequest } from './access-control';
import type { WorkerEnv } from './env';

type Summary = { whatsapp: string | null; email: string | null; email_verified_at: string | null; projects: number; jira: number; pending: number; failed: number };
type Event = { integration: string; event_type: string; project_name: string | null; created_at: string };
const esc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

function page(body:string,status=200):Response {
	return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Integration health · Dutha</title><style>:root{font-family:Inter,Arial,sans-serif;color:#dbeafe;background:#070b18}*{box-sizing:border-box}body{margin:0;padding:28px;min-height:100vh;background:radial-gradient(circle at 10% 0,#172554 0,transparent 36%),radial-gradient(circle at 95% 4%,#312e81 0,transparent 30%),#070b18}main{max-width:1100px;margin:auto}.head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:24px}h1,h2{color:#f8fafc;margin:0 0 8px}.muted{color:#94a3b8;line-height:1.5}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.13em;color:#60a5fa}.button{display:inline-block;border-radius:10px;padding:11px 15px;background:#263b70;color:#fff;text-decoration:none;font-weight:800}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.card{background:#111827e8;border:1px solid #334155;border-radius:16px;padding:19px;box-shadow:0 16px 42px #0004}.state{display:inline-block;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:800;background:#3f2d17;color:#fcd34d}.state.ok{background:#123b34;color:#86efac}.state.off{background:#263244;color:#cbd5e1}.card p{min-height:40px}.card a{color:#bfdbfe;font-weight:800}.numbers{display:flex;gap:12px;margin:18px 0}.metric{flex:1;background:#0b1220;border:1px solid #263244;padding:14px;border-radius:12px}.metric strong{display:block;font-size:23px;color:white}.metric span{font-size:12px;color:#94a3b8}.activity{margin-top:18px}.row{display:grid;grid-template-columns:130px 1fr auto;gap:12px;align-items:center;border-top:1px solid #263244;padding:13px 0}.row:first-of-type{margin-top:14px}.tag{text-transform:capitalize;color:#bfdbfe;font-weight:800}.empty{padding:24px;text-align:center;color:#94a3b8;background:#0b1220;border-radius:12px}@media(max-width:720px){body{padding:16px}.grid{grid-template-columns:1fr}.head{flex-direction:column}.row{grid-template-columns:1fr;gap:4px}.numbers{flex-direction:column}}</style></head><body><main>${body}</main></body></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'"}});
}

export async function integrationHealthResponse(request:Request,env:WorkerEnv):Promise<Response> {
	const actor=managementPrincipalFromRequest(request);
	if(!actor) return new Response('Authentication required.',{status:401});
	if(!['admin','ceo'].includes(actor.role)) return new Response('CEO or Administrator access required.',{status:403});
	if(request.method!=='GET') return new Response('Method not allowed.',{status:405});
	const [s,events]=await Promise.all([
		env.DB.prepare(`SELECT (SELECT connection_status FROM organisation_whatsapp_connections WHERE tenant_id=? LIMIT 1) AS whatsapp,(SELECT email_connection_status FROM organisation_email_settings WHERE tenant_id=? LIMIT 1) AS email,(SELECT email_last_verified_at FROM organisation_email_settings WHERE tenant_id=? LIMIT 1) AS email_verified_at,(SELECT COUNT(*) FROM projects WHERE tenant_id=? AND active=1) AS projects,(SELECT COUNT(*) FROM project_jira_connections WHERE tenant_id=? AND connection_status='connected') AS jira,(SELECT COUNT(*) FROM channel_notification_outbox WHERE tenant_id=? AND delivery_status IN ('pending','sending')) AS pending,(SELECT COUNT(*) FROM channel_notification_outbox WHERE tenant_id=? AND delivery_status='failed') AS failed`).bind(actor.tenantId,actor.tenantId,actor.tenantId,actor.tenantId,actor.tenantId,actor.tenantId,actor.tenantId).first<Summary>(),
		env.DB.prepare(`SELECT event.integration,event.event_type,project.name AS project_name,event.created_at FROM integration_operation_events AS event LEFT JOIN projects AS project ON project.id=event.project_id AND project.tenant_id=event.tenant_id WHERE event.tenant_id=? ORDER BY event.created_at DESC,event.id DESC LIMIT 12`).bind(actor.tenantId).all<Event>(),
	]);
	const summary=s??{whatsapp:null,email:null,email_verified_at:null,projects:0,jira:0,pending:0,failed:0};
	const badge=(ok:boolean,label:string)=>`<span class="state ${ok?'ok':'off'}">${label}</span>`;
	const waOk=summary.whatsapp==='connected',emailOk=summary.email==='connected',jiraOk=summary.jira>0;
	const eventRows=(events.results??[]).map((e)=>`<div class="row"><span class="tag">${esc(e.integration)} · ${esc(e.event_type.replaceAll('_',' '))}</span><span>${esc(e.project_name||'Organisation event')}</span><span class="muted">${esc(e.created_at)}</span></div>`).join('');
	const body=`<header class="head"><div><div class="eyebrow">ORGANISATION CONTROL</div><h1>Integration health</h1><div class="muted">Connection status and recent delivery recovery signals for your company.</div></div><a class="button" href="/dashboard/settings">Connection hub</a></header><section class="grid"><article class="card"><div class="eyebrow">WHATSAPP</div><h2>Business messaging</h2><p class="muted">Company sender connection for employee updates and coordination.</p>${badge(waOk,waOk?'Connected':'Needs setup')}<p><a href="/dashboard/whatsapp">Open WhatsApp setup →</a></p></article><article class="card"><div class="eyebrow">EMAIL</div><h2>Company email</h2><p class="muted">Sender identity and provider connection for outgoing email.</p>${badge(emailOk,emailOk?'Connected':summary.email==='disconnected'?'Disconnected':'Needs setup')}${summary.email_verified_at?`<p class="muted">Verified ${esc(summary.email_verified_at)}</p>`:''}<p><a href="/dashboard/email">Open email setup →</a></p></article><article class="card"><div class="eyebrow">JIRA</div><h2>Project connections</h2><p class="muted">Projects with an active Jira connection.</p>${badge(jiraOk,`${summary.jira} connected`)}<p><a href="/dashboard/projects">Manage projects →</a></p></article></section><section class="card activity"><div class="eyebrow">DELIVERY QUEUE</div><h2>Pending and failed notifications</h2><div class="numbers"><div class="metric"><strong>${summary.pending}</strong><span>Pending or sending</span></div><div class="metric"><strong>${summary.failed}</strong><span>Failed deliveries to review</span></div><div class="metric"><strong>${summary.projects}</strong><span>Active projects</span></div></div><p class="muted">Counts are scoped to your organisation. Failed records remain available for the existing retry process.</p></section><section class="card activity"><div class="eyebrow">RECENT OPERATIONS</div><h2>Recovery activity</h2>${eventRows||'<div class="empty">No retry or recovery events have been recorded for this organisation yet.</div>'}</section>`;
	return page(body);
}
