import { accessibleProjects, managementPrincipalFromRequest, requireProjectAccess, type ManagementPrincipal } from './access-control';
import type { WorkerEnv } from './env';
import { decryptIntegrationSecret, encryptIntegrationSecret } from './integration-secrets';

type StoredConnection={base_url:string;account_email:string;api_token_ciphertext:string;api_token_iv:string;project_key:string;issue_type:string;connection_status:string;last_verified_at:string};
type Fetcher=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;
const esc=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

function basicAuth(request:Request,env:WorkerEnv):boolean {
	return Boolean(env.DASHBOARD_USERNAME&&env.DASHBOARD_PASSWORD&&request.headers.get('Authorization')===`Basic ${btoa(`${env.DASHBOARD_USERNAME}:${env.DASHBOARD_PASSWORD}`)}`);
}
function sameOrigin(request:Request):boolean {
	const origin=request.headers.get('Origin'); return origin&&origin!=='null'?origin===new URL(request.url).origin:request.headers.get('Sec-Fetch-Site')==='same-origin';
}
function html(body:string,status=200):Response {
	return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jira connection · Dutha</title><style>:root{font-family:Inter,Arial,sans-serif;color:#e2e8f0;background:#070b18}*{box-sizing:border-box}body{margin:0;padding:28px;background:radial-gradient(circle at 8% 0,#1e3a8a 0,transparent 35%),radial-gradient(circle at 94% 4%,#312e81 0,transparent 32%),#070b18}main{max-width:920px;margin:auto}.head{display:flex;justify-content:space-between;align-items:start;gap:14px}.card{background:#111827e8;border:1px solid #334155;border-radius:18px;padding:22px;margin:18px 0;box-shadow:0 18px 48px #0006}h1,h2{color:#f8fafc;margin-top:0}.eyebrow{color:#93c5fd;font-size:11px;font-weight:900;letter-spacing:.12em}.muted{color:#94a3b8;line-height:1.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:7px;font-weight:700;margin:12px 0}input,select{font:inherit;padding:11px;border:1px solid #475569;border-radius:9px;background:#0b1220;color:#f8fafc;width:100%}button,.button{border:0;border-radius:9px;padding:11px 15px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#334155}.pill{display:inline-block;padding:6px 10px;border-radius:99px;background:#312e81;color:#ddd6fe;font-size:12px;font-weight:800}.ok{background:#1e3a8a;color:#bfdbfe}.banner{padding:12px;border-radius:10px;background:#172554;color:#bfdbfe}.error{background:#450a0a;color:#fecaca}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:15px}code{overflow-wrap:anywhere}@media(max-width:680px){body{padding:14px}.head{flex-direction:column}.grid{grid-template-columns:1fr}.card{padding:17px}}</style></head><body><main>${body}</main></body></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'"}});
}
function validBaseUrl(value:string):string|null {
	try { const u=new URL(value); if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||!u.hostname.endsWith('.atlassian.net')||u.hostname==='atlassian.net') return null; return u.toString().replace(/\/$/,''); } catch { return null; }
}
function principal(request:Request):ManagementPrincipal { return managementPrincipalFromRequest(request)??{userId:1,tenantId:1,role:'admin'}; }

async function render(request:Request,env:WorkerEnv,actor:ManagementPrincipal,projectId:number,fetcher:Fetcher,message='',error=''):Promise<Response> {
	const projects=await accessibleProjects(env.DB,actor);
	const project=projects.find(p=>p.id===projectId);
	const stored=await env.DB.prepare(`SELECT base_url,account_email,api_token_ciphertext,api_token_iv,project_key,issue_type,connection_status,last_verified_at FROM project_jira_connections WHERE tenant_id=? AND project_id=? LIMIT 1`).bind(actor.tenantId,projectId).first<StoredConnection>();
	const status=stored?.connection_status==='connected';
	const notice=message?`<p class="banner">${esc(message)}</p>`:''; const alert=error?`<p class="banner error">${esc(error)}</p>`:'';
	const picker=projects.length>1?`<form method="get"><label>Project<select name="project">${projects.map(p=>`<option value="${p.id}"${p.id===projectId?' selected':''}>${esc(p.project_key)} · ${esc(p.name)}</option>`).join('')}</select></label><button type="submit">Open project</button></form>`:'';
	return html(`<header class="head"><div><div class="eyebrow">PROJECT INTEGRATION</div><h1>Jira connection</h1><p class="muted">${esc(project?.project_key??'Project')} · ${esc(project?.name??'')}</p></div><div class="actions"><a class="button secondary" href="/dashboard?project=${projectId}">Dashboard</a></div></header>${notice}${alert}${picker}<section class="card"><div class="head"><div><h2>Outbound Jira sync</h2><p class="muted">Connect an Atlassian Cloud site. Dutha tests the account and project before saving. The API token is encrypted with AES-GCM in D1 and never shown again.</p></div><span class="pill ${status?'ok':''}">${status?'Connected':'Needs setup'}</span></div>${status?`<p class="muted">Verified ${esc(stored!.last_verified_at)} · account ${esc(stored!.account_email)} · Jira project ${esc(stored!.project_key)}</p>`:''}<form method="post" action="/dashboard/jira?project=${projectId}"><input type="hidden" name="project_id" value="${projectId}"><div class="grid"><label>Jira site URL<input name="base_url" type="url" placeholder="https://company.atlassian.net" value="${esc(stored?.base_url)}" required></label><label>Jira account email<input name="account_email" type="email" maxlength="254" value="${esc(stored?.account_email)}" required></label><label>Jira project key<input name="project_key" maxlength="10" pattern="[A-Z][A-Z0-9_]{1,9}" value="${esc(stored?.project_key)}" placeholder="OPS" required></label><label>Issue type<input name="issue_type" maxlength="80" value="${esc(stored?.issue_type??'Task')}" required></label></div><label>Jira API token<input name="api_token" type="password" autocomplete="new-password" maxlength="500" placeholder="${status?'Leave blank to keep the saved token':'Paste the project API token'}" ${status?'':'required'}></label><p class="muted">The connection test checks Jira’s current-user endpoint and confirms the project key is accessible. Your token is encrypted before storage; Dutha cannot display the saved value.</p><div class="actions"><button type="submit">Test and save connection</button></div></form></section><section class="card"><h2>Webhook status</h2><p class="muted">This release uses the existing configured Jira webhook secret for status callbacks. Per-company webhook-secret routing is a separate step; outbound issue creation and retries use this project connection.</p></section>`);
}

export async function jiraConnectionManagementResponse(request:Request,env:WorkerEnv,fetcher:Fetcher=fetch):Promise<Response> {
	if (!basicAuth(request,env)) return new Response('Authentication required.',{status:401,headers:{'WWW-Authenticate':'Basic realm="Dutha WorkOps"'}});
	const actor=principal(request); if (!['admin','ceo','project_manager'].includes(actor.role)) return new Response('Administrator, CEO, or project manager access required.',{status:403});
	const url=new URL(request.url); const form=request.method==='POST'?await request.clone().formData():null; const projectId=Number(form?.get('project_id')??url.searchParams.get('project')??1);
	if(!Number.isSafeInteger(projectId)||projectId<=0) return new Response('Invalid project.',{status:400});
	try { await requireProjectAccess(env.DB,actor,projectId); } catch { return new Response('Project access denied.',{status:403}); }
	if(request.method==='GET') return render(request,env,actor,projectId,fetcher,url.searchParams.get('saved')?'Jira connection verified and saved.':'');
	if(request.method!=='POST') return new Response('Method not allowed.',{status:405,headers:{Allow:'GET, POST'}});
	if(!sameOrigin(request)) return new Response('Invalid request origin.',{status:403});
	if(!env.INTEGRATION_ENCRYPTION_KEY) return render(request,env,actor,projectId,fetcher,'','Integration encryption is not configured. Ask the administrator to add the INTEGRATION_ENCRYPTION_KEY Worker secret, then retry.');
	const posted=form!; const baseUrl=validBaseUrl(String(posted.get('base_url')??'').trim()); const email=String(posted.get('account_email')??'').trim().toLowerCase(); const projectKey=String(posted.get('project_key')??'').trim().toUpperCase(); const issueType=String(posted.get('issue_type')??'Task').trim(); let apiToken=String(posted.get('api_token')??'').trim();
	if(!baseUrl||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||!/^[A-Z][A-Z0-9_]{1,9}$/.test(projectKey)||!issueType||issueType.length>80||apiToken.length>500) return render(request,env,actor,projectId,fetcher,'','Check the Jira site, account email, project key, issue type, and API token.');
	const existing=await env.DB.prepare(`SELECT api_token_ciphertext,api_token_iv FROM project_jira_connections WHERE tenant_id=? AND project_id=?`).bind(actor.tenantId,projectId).first<{api_token_ciphertext:string;api_token_iv:string}>();
	if(!apiToken&&existing) { try { apiToken=await decryptIntegrationSecret(existing.api_token_ciphertext,existing.api_token_iv,env.INTEGRATION_ENCRYPTION_KEY,actor.tenantId,projectId,'jira','api_token'); } catch { return render(request,env,actor,projectId,fetcher,'','Saved credential could not be decrypted. Re-enter the Jira API token.'); } }
	if(apiToken.length<8) return render(request,env,actor,projectId,fetcher,'','Enter a Jira API token.');
	const authorization=`Basic ${btoa(`${email}:${apiToken}`)}`;
	try {
		const who=await fetcher(`${baseUrl}/rest/api/3/myself`,{headers:{Authorization:authorization,Accept:'application/json'}});
		if(!who.ok) return render(request,env,actor,projectId,fetcher,'',`Jira account verification failed (HTTP ${who.status}). Check the site, email, and token.`);
		const project=await fetcher(`${baseUrl}/rest/api/3/project/${encodeURIComponent(projectKey)}`,{headers:{Authorization:authorization,Accept:'application/json'}});
		if(!project.ok) return render(request,env,actor,projectId,fetcher,'',`Jira project verification failed (HTTP ${project.status}). Check the project key and account access.`);
	} catch { return render(request,env,actor,projectId,fetcher,'','Could not reach Jira over HTTPS. Check the Jira site URL and try again.'); }
	const encrypted=await encryptIntegrationSecret(apiToken,env.INTEGRATION_ENCRYPTION_KEY,actor.tenantId,projectId,'jira','api_token'); const verifiedAt=new Date().toISOString();
	await env.DB.prepare(`INSERT INTO project_jira_connections (tenant_id,project_id,base_url,account_email,api_token_ciphertext,api_token_iv,project_key,issue_type,connection_status,configured_by_management_user_id,last_verified_at) VALUES (?,?,?,?,?,?,?,?,'connected',?,?) ON CONFLICT(tenant_id,project_id) DO UPDATE SET base_url=excluded.base_url,account_email=excluded.account_email,api_token_ciphertext=excluded.api_token_ciphertext,api_token_iv=excluded.api_token_iv,project_key=excluded.project_key,issue_type=excluded.issue_type,connection_status='connected',configured_by_management_user_id=excluded.configured_by_management_user_id,last_verified_at=excluded.last_verified_at,updated_at=CURRENT_TIMESTAMP`).bind(actor.tenantId,projectId,baseUrl,email,encrypted.ciphertext,encrypted.iv,projectKey,issueType,actor.userId,verifiedAt).run();
	return new Response(null,{status:303,headers:{Location:`/dashboard/jira?project=${projectId}&saved=1`,'Cache-Control':'no-store'}});
}
