export const duthaThemeCss = `
:root{color-scheme:light;--d-ink:#17263b;--d-muted:#65758a;--d-line:rgba(96,119,142,.2);--d-glass:rgba(253,254,253,.76);--d-surface:rgba(255,255,255,.82);--d-nav:#183f4a;--d-nav2:#326d70;--d-teal:#57b9aa;--d-blue:#7c91d9;--d-bg:#f2f5f1;--d-glow1:#d9eee8;--d-glow2:#e8e5f4;--d-shadow:0 24px 70px rgba(36,58,68,.13)}
:root[data-theme=dark]{color-scheme:dark;--d-ink:#edf5f3;--d-muted:#aabbbd;--d-line:rgba(207,229,226,.14);--d-glass:rgba(20,31,39,.76);--d-surface:rgba(30,44,53,.86);--d-nav:#101d27;--d-nav2:#173b43;--d-teal:#70d4c0;--d-blue:#98a9ec;--d-bg:#0d171f;--d-glow1:#163d3b;--d-glow2:#242845;--d-shadow:0 24px 80px rgba(0,0,0,.38)}
body{color:var(--d-ink)!important;background:radial-gradient(circle at 12% 10%,var(--d-glow1) 0,transparent 30%),radial-gradient(circle at 92% 2%,var(--d-glow2) 0,transparent 34%),var(--d-bg)!important;transition:background .3s,color .3s}.card,.table-wrap,.shell{background:var(--d-surface)!important;border:1px solid var(--d-line)!important;box-shadow:var(--d-shadow)!important}h1,h2,.value{color:var(--d-ink)!important}.subtitle,.muted,.label,footer,td small{color:var(--d-muted)!important}input,select,textarea{background:var(--d-surface)!important;color:var(--d-ink)!important;border-color:var(--d-line)!important}.navigation a,.button,button{border-radius:11px!important}.navigation a:not(.cases),button:not(.theme-toggle){background:var(--d-nav)!important}.theme-toggle{width:42px;height:42px;padding:0!important;border:1px solid var(--d-line)!important;border-radius:50%!important;background:var(--d-surface)!important;color:var(--d-ink)!important;font-size:18px!important;box-shadow:none!important}.dutha-theme-corner{position:fixed;right:18px;bottom:18px;z-index:999}.table-wrap{border-radius:18px!important}th{background:var(--d-nav)!important}td{border-color:var(--d-line)!important}@media(prefers-reduced-motion:reduce){*,*::before,*::after{transition-duration:.01ms!important;animation-duration:.01ms!important}}
`;

export const themeButton = `<button type="button" class="theme-toggle" data-dutha-theme aria-label="Switch colour theme" title="Switch colour theme">◐</button>`;
export const themeScriptTag = `<script src="/assets/dutha-ui.js" defer></script>`;

export function duthaUiScriptResponse(): Response {
	return new Response(`(()=>{const r=document.documentElement,k='dutha-theme',b=()=>document.querySelectorAll('[data-dutha-theme]');let t;try{t=localStorage.getItem(k)}catch{}if(t!=='light'&&t!=='dark')t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';const a=()=>{r.dataset.theme=t;b().forEach(x=>x.textContent=t==='dark'?'☀':'☾')};a();addEventListener('click',e=>{const x=e.target.closest('[data-dutha-theme]');if(!x)return;t=t==='dark'?'light':'dark';try{localStorage.setItem(k,t)}catch{}a()})})();`, { headers:{ 'Content-Type':'application/javascript; charset=utf-8', 'Cache-Control':'public, max-age=3600', 'X-Content-Type-Options':'nosniff' } });
}

export function publicLandingResponse(): Response {
	return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dutha WorkOps</title><style>${duthaThemeCss}:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh}.top{max-width:1180px;margin:auto;padding:22px 28px;display:flex;justify-content:space-between;align-items:center}.logo{font-size:21px;font-weight:900;letter-spacing:-.04em}.hero{max-width:1050px;margin:7vh auto;padding:40px 28px;text-align:center}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.15em;font-weight:850;color:var(--d-teal)}h1{font-size:clamp(42px,7vw,76px);line-height:1.02;letter-spacing:-.06em;margin:16px auto;max-width:900px}.hero p{font-size:19px;color:var(--d-muted);max-width:690px;margin:0 auto 30px}.actions{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}.actions a{padding:13px 19px;border-radius:12px;text-decoration:none;font-weight:800;background:var(--d-nav);color:#fff}.actions a.secondary{background:var(--d-surface);color:var(--d-ink);border:1px solid var(--d-line)}.glass{margin:45px auto 0;max-width:880px;padding:22px;border-radius:24px;background:var(--d-glass);border:1px solid var(--d-line);box-shadow:var(--d-shadow);display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.glass div{padding:18px;border-radius:16px;background:var(--d-surface)}.glass strong{display:block;font-size:18px}@media(max-width:650px){.glass{grid-template-columns:1fr}.hero{margin-top:2vh}}</style>${themeScriptTag}</head><body><header class="top"><div class="logo">◈ Dutha WorkOps</div>${themeButton}</header><main class="hero"><div class="eyebrow">The calm operating layer for modern teams</div><h1>Work moves better when everyone is aligned.</h1><p>Dutha turns daily updates, blockers and coordination into one clear operating rhythm.</p><div class="actions"><a href="/login">Management workspace</a><a class="secondary" href="/employee/login">Employee workspace</a></div><section class="glass"><div><strong>Daily clarity</strong><span>Structured updates without meetings.</span></div><div><strong>Faster coordination</strong><span>Blockers move to the right owner.</span></div><div><strong>Verified closure</strong><span>Jira and employee confirmation.</span></div></section></main></body></html>`, { headers:{ 'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'" } });
}
